---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: node-ipc-pvc
  namespace: cardano
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: node-db-pvc
  namespace: cardano
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: cardano-node
  namespace: cardano
spec:
  selector:
    app: cardano-node
  ports:
    - protocol: TCP
      port: 12788
      targetPort: 12788
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cardano-node
  namespace: cardano
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cardano-node
  template:
    metadata:
      labels:
        app: cardano-node
    spec:
      containers:
        - name: cardano-node
          image: ghcr.io/intersectmbo/cardano-node:10.1.4
          env:
            - name: NETWORK
              value: "preprod"
          volumeMounts:
            - name: node-db-storage
              mountPath: /data/db
            - name: ipc
              mountPath: /ipc
          ports:
            - containerPort: 12788
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - test -S /ipc/node.socket
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 5
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - test -S /ipc/node.socket
            initialDelaySeconds: 5
            periodSeconds: 3
            failureThreshold: 3
      volumes:
        - name: node-db-storage
          persistentVolumeClaim:
            claimName: node-db-pvc
        - name: ipc
          persistentVolumeClaim:
            claimName: node-ipc-pvc




